const stickers = {
  // 呆呆
  "wow" : "CAADBQADUgADJZO8Fktt4y20_XaQAg",
  "wow!" : "CAADBQADTwADJZO8FuiRZOTanyWEAg",
  "daidai" : "CAADBQADRQADJZO8FsuhYE3anrL-Ag",

  // 蠢熊
  "贊成" : "CAADAQADnhAAAvoPCRSBPyCtg_UR-gI",
  "反對" : "CAADAQADnRAAAvoPCRQ9GSIFooLZ8QI",
  "厲害的人" : "CAADBQADLwADGmbGFWQ7aCEmtuCWAg",

  // 蠢熊3.5
  "踢踢" : "CAADBQADPAAD10JZFXfWhUXxM12mAg",
  "躺下" : "CAADBQADPQAD10JZFWBiigu8ftRPAg",
  "爬起" : "CAADBQADPgAD10JZFUH2OAfH9UzDAg",
  "滾滾" : "CAADBQADPwAD10JZFZdGN0nG8907Ag",
  "倒下" : "CAADBQADQAAD10JZFXXYetnHn5BMAg",
  "走來走去" : ["CAADBQADRgAD10JZFXDN9YPQHVgiAg", "CAADBQADRwAD10JZFQbZlU1vUlz6Ag"],
  "跳來跳去" : ["CAADBQADSAAD10JZFUNlohbgBVuQAg", "CAADBQADSQAD10JZFTcoXgAB7VdpUgI"],
  "寫" : "CAADBQADSwAD10JZFRyVzUz939XzAg",
  "擦擦" : "CAADBQADTAAD10JZFSUG8nCi0HHAAg",
  "隱形" : "CAADBQADTgAD10JZFS8Tjh0Pz1VUAg",
  "微笑" : "CAADBQADUwAD10JZFb2Ho9woqyVuAg",
  "含淚" : "CAADBQADVAAD10JZFaA1yv0GpNi0Ag",
  "抓住" : "CAADBQADWAAD10JZFQABAmuOb1ws6gI",
  "飛走" : "CAADBQADWQAD10JZFZhpu6UJ8hH2Ag"
}

module.exports = stickers
